image:
  repository: grafana/promtail
  tag: "2.9.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

loki:
  url: http://loki:3100/loki/api/v1/push
