apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    {{- toYaml .Values.config | nindent 4 }}
