apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
data:
  config.yaml: |
    clients:
      - url: {{ .Values.loki.url }}
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: replace
            target_label: container
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_container_name
            separator: /
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            separator: /
            target_label: __path__
            regex: (.*)/(.*); /var/log/pods/\1/\2/**.log
